<?php
use yii\db\Migration;

class m140123_121958_initialize_schema extends Migration
{
	public function up()
	{
		$sql = "
		-- MySQL Script generated by MySQL Workbench
        -- 02/06/15 16:39:59
        -- Model: New Model    Version: 1.0
        -- MySQL Workbench Forward Engineering

        SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
        SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
        SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

        -- -----------------------------------------------------
        -- Schema surveys_for_a_cause
        -- -----------------------------------------------------

        -- -----------------------------------------------------
        -- Table `UserType`
        -- -----------------------------------------------------
        CREATE TABLE IF NOT EXISTS `UserType` (
          `userTypeId` INT NOT NULL AUTO_INCREMENT,
          `dateCreated` DATETIME NULL,
          `dateLastModified` DATETIME NULL,
          `userTypeName` VARCHAR(45) NULL,
          PRIMARY KEY (`userTypeId`))
        ENGINE = InnoDB;


        -- -----------------------------------------------------
        -- Table `UserStatus`
        -- -----------------------------------------------------
        CREATE TABLE IF NOT EXISTS `UserStatus` (
          `userStatusId` INT NOT NULL AUTO_INCREMENT,
          `dateCreated` DATETIME NULL,
          `dateLastModified` DATETIME NULL,
          PRIMARY KEY (`userStatusId`))
        ENGINE = InnoDB;


        -- -----------------------------------------------------
        -- Table `User`
        -- -----------------------------------------------------
        CREATE TABLE IF NOT EXISTS `User` (
          `userId` INT NOT NULL AUTO_INCREMENT,
          `dateCreated` DATETIME NULL,
          `dateLastModified` DATETIME NULL,
          `userName` VARCHAR(256) NULL,
          `userEmail` VARCHAR(256) NULL,
          `userPassword` VARCHAR(256) NULL,
          `userTypeId` INT NOT NULL,
          `userStatusId` INT NOT NULL,
          `userIglobalMemberId` INT NULL,
          PRIMARY KEY (`userId`),
          INDEX `fk_User_UserType_idx` (`userTypeId` ASC),
          INDEX `fk_User_UserStatus1_idx` (`userStatusId` ASC),
          CONSTRAINT `fk_User_UserType`
            FOREIGN KEY (`userTypeId`)
            REFERENCES `UserType` (`userTypeId`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
          CONSTRAINT `fk_User_UserStatus1`
            FOREIGN KEY (`userStatusId`)
            REFERENCES `UserStatus` (`userStatusId`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION)
        ENGINE = InnoDB;


        -- -----------------------------------------------------
        -- Table `SiteSession`
        -- -----------------------------------------------------
        CREATE TABLE IF NOT EXISTS `SiteSession` (
          `id` VARCHAR(32) NOT NULL,
          `expire` INT(11) NULL,
          `data` LONGBLOB NULL,
          PRIMARY KEY (`id`),
          INDEX `expire` (`expire` ASC))
        ENGINE = InnoDB;


        -- -----------------------------------------------------
        -- Table `UserConfirmation`
        -- -----------------------------------------------------
        CREATE TABLE IF NOT EXISTS `UserConfirmation` (
          `userConfirmationId` INT NOT NULL AUTO_INCREMENT,
          `dateCreated` DATETIME NULL,
          `dateLastModified` DATETIME NULL,
          `userConfirmationcCode` VARCHAR(128) NULL,
          `userId` INT NOT NULL,
          PRIMARY KEY (`userConfirmationId`),
          INDEX `fk_UserConfirmation_User1_idx` (`userId` ASC),
          CONSTRAINT `fk_UserConfirmation_User1`
            FOREIGN KEY (`userId`)
            REFERENCES `User` (`userId`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION)
        ENGINE = InnoDB;


        SET SQL_MODE=@OLD_SQL_MODE;
        SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
        SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
		";
		$this->execute($sql);
	}

	public function down()
	{
		//echo "m140123_121958_initialize_schema does not support migration down.\n";
		//return false;
	}

	/*
	// Use safeUp/safeDown to do migration with transaction
	public function safeUp()
	{
	}

	public function safeDown()
	{
	}
	*/
}